# Generated by Django 3.1.5 on 2021-04-05 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fball_calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='player',
            name='FTeam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fball_calculator.team'),
        ),
    ]
