# Generated by Django 3.1.5 on 2021-04-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fball_calculator', '0002_auto_20210405_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='Position',
            field=models.CharField(choices=[('', 'Blank'), ('G', 'Guard'), ('F', 'Forward'), ('C', 'Center')], max_length=1, null=True),
        ),
    ]
