# Generated by Django 3.1.5 on 2021-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fball_calculator', '0003_player_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='Position',
        ),
        migrations.AddField(
            model_name='player',
            name='Pos',
            field=models.ManyToManyField(to='fball_calculator.Positions'),
        ),
    ]
