# Generated by Django 3.1.5 on 2021-04-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fball_calculator', '0004_auto_20210412_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='FTeamPos',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AddField(
            model_name='player',
            name='PosStr',
            field=models.CharField(default='', max_length=3),
        ),
    ]
